f <- file("stdin")
open(f)
d <- strsplit(readLines(f, warn=FALSE), split=" ")
numbers<-as.numeric(d[[2]])
weights<-as.numeric(d[[3]])
cat(format(round(weighted.mean(numbers, weights), digits=1), nsmall=1), "\n")
